apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: deploy-app
  namespace: kabanero
  author: Andrew Suh
  date: 05/22/20
spec:
  inputs:
    params:
      - name: namespace
        default: ""
        type: string
      - name: cf-org
        description: Specify the Cloud Foundry org to run in.
        default: ""
      - name: cf-space
        description: Specify the Cloud Foundry space to run in.
        default: ""
      - name: cf-app-name
        description: What to name the application on Cloud Foundry.
        default: ""
      - name: api-endpoint
        description: Supply an endpoint url if needed
        default: ""
    resources:
      - name: source
        type: git
      - name: image
        type: image
  steps:
    - name: deploying-app
      image: $(inputs.resources.image.url)
  command: ["/bin/bash"]
  args:
    - -c
    - |
      set -euxo pipefail

      oc project ${namespace}

      if [ ${api-endpoint}="" ]
      then
        continue
      else
        cf api ${api-endpoint}
      fi

      cf auth ${cf-username} ${cf-password}

      cf target -o ${cf-org} -s ${cf-space}

      git clone https://github.com/andrew-suh/storefront-ui

      cd storefront-ui

      cf push -f ./manifest.yml storefront-ui-app

  env:
    - name: namespace
      value: $(inputs.params.namespace)
    - name: cf-org
      value: $(inputs.params.cf-org)
    - name: cf-space
      value: $(inputs.params.cf-space)
    - name: cf-app-name
      value: $(inputs.params.cf-app-name)
    - name: api-endpoint
      value: $(inputs.params.api-endpoint)
    - name: cf-username
      valueFrom:
        secretKeyRef:
          name: cf-access
          key: CF_USERNMAME
    - name: cf-password
      valueFrom:
        secretKeyRef:
          name: cf-access
          key: CF_PASSWORD
  resources: {}
  workingDir: $(inputs.resources.source.path)
