apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: deploy-app
  namespace: kabanero
  author: Andrew Suh
  date: 05/22/20
spec:
  inputs:
    params:
      - name: cf_org
        description: Specify the Cloud Foundry org to run in.
      - name: cf_space
        description: Specify the Cloud Foundry space to run in.
      - name: cf_app_name
        description: What to name the application on Cloud Foundry.
      - name: api_endpoint
        description: Supply an endpoint url if needed
    resources:
      - name: source
        type: git
      - name: image
        type: image
  steps:
    - name: deploying-app
      image: $(inputs.resources.image.url)
      command: ["/bin/bash"]
      args:
        - -c
        - |
          set -euxo pipefail

          if [ ${api-endpoint}="" ]
          then
            continue
          else
            cf api ${api-endpoint}
          fi

          cf auth ${cf-username} ${cf-password}

          cf target -o ${cf-org} -s ${cf-space}

          git clone https://github.com/andrew-suh/storefront-ui

          cd storefront-ui

          cf push -f ./manifest.yml storefront-ui-app

      env:
        - name: cf_org
          value: $(inputs.params.cf_org)
        - name: cf_space
          value: $(inputs.params.cf_space)
        - name: cf_app_name
          value: $(inputs.params.cf_app_name)
        - name: api_endpoint
          value: $(inputs.params.api_endpoint)
        - name: cf_username
          valueFrom:
            secretKeyRef:
              name: cf-access
              key: CF_USERNMAME
        - name: cf-password
          valueFrom:
            secretKeyRef:
              name: cf-access
              key: CF_PASSWORD
      resources: {}
      workingDir: $(inputs.resources.source.path)
