apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: cf-deployment-pl
  namespace: kabanero
  author: Andrew Suh
  date: 05/22/20
spec:
  params:
    - name: namespace
      description: Specify the namespace to run the pipeline in.
      default: ""
    - name: cf-org
      description: Specify the Cloud Foundry org to run in.
      default: ""
    - name: cf-space
      description: Specify the Cloud Foundry space to run in.
      default: ""
    - name: cf-app-name
      description: What to name the application on Cloud Foundry.
      default: ""
    - name: api-endpoint
      description: Supply an endpoint url if needed
      default: ""
  resources:
    - name: git-source
      type: git
    - name: docker-image
      type: image
  tasks:
    - name: deploy-app
      resources:
        inputs:
          - name: source
            resource: git-source
          - name: image
            resource: docker-image
      params:
        - name: namespace
          value: $(params.namespace)
        - name: cf-org
          value: $(params.cf-org)
        - name: cf-space
          value: $(params.cf-space)
        - name: cf-app-name
          value: $(params.cf-app-name)
        - name: api-endpoint
          value: $(params.api-endpoint)
      taskRef:
        kind: Task
        name: create-release-for-git-task