# The responsibility of this pipeline is to deploy an app
# such as the storefront application onto ibm cloud CF.
apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: deploy-app-ibm-cloud-pl
  namespace: kabanero
  author: Oscar Ricaud
  date: 05/26/20
spec:
  params:
    - name: namespace
      description: namespace we want to deploy the app at
      default: docker.io
    - name: cf-org
      description: specify the cloud foundry org to run in
      default: 'true'
    - name: cf-space
      description: name of the cloud foundry space to run in
      default: healthcheck-pipeline
    - name: cf-app-name
      description: name of application
      default: ""
    - name: event-type
      description: The event type
      type: string
    - name: event-ref
      description: The event ref
      type: string
  resources:
    - name: git-source
      type: git
    - name: docker-image
      type: image
  tasks:
    - name: deploy-app-ibmcloud
      resources:
        inputs:
          - name: source
            resource: git-source
          - name: image
            resource: docker-image
      params:
        - name: namespace
          value: $(params.namespace)
        - name: cf-org
          value: $(params.cf-org)
        - name: cf-space
          value: $(params.cf-space)
        - name: cf-app-name
          value: $(params.cf-app-name)   
      taskRef:
        kind: Task
        name: deploy-app-ibmcloud-task