# The responsibility of this pipeline is to deploy an app
# such as the storefront application onto ibm cloud CF.
apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: deploy-app-ibm-cloud-pl
  namespace: kabanero
  author: Oscar Ricaud
  date: 05/26/20
spec:
  params:
    - name: registry
      description: Specify the registry url.
      default: docker.io
    - name: image-registry-publish
      description: determines if we want to push the image to a registry
      default: 'true'
    - name: index-image
      description: name of image
      default: healthcheck-pipeline
    - name: event-type
      description: The event type
      type: string
    - name: event-ref
      description: The event ref
      type: string
  resources:
    - name: git-source
      type: git
    - name: docker-image
      type: image
  tasks:
    - name: deploy-app-ibm-cloud
      resources:
        inputs:
          - name: source
            resource: git-source
          - name: image
            resource: docker-image
      params:
        - name: registry
          value: $(params.registry)
        - name: index-image
          value: $(params.index-image)
        - name: image-registry-publish
          value: $(params.image-registry-publish)
      taskRef:
        kind: Task
        name: create-release-for-git-task