apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: deploy-app-ibmcloud-task
  namespace: kabanero
  author: Oscar Ricaud
  date: 05/26/20
spec:
  inputs:
    params:
      - name: namespace
        default: ""
        type: string
      - name: cf-org
        description: Specify the Cloud Foundry org to run in.
        default: ""
      - name: cf-space
        description: Specify the Cloud Foundry space to run in.
        default: ""
      - name: cf-app-name
        description: What to name the application on Cloud Foundry.
        default: ""
    resources:
      - name: source
        type: git
      - name: image
        type: image
  steps:
    - name: deploying-app
      image: $(inputs.resources.image.url)
  command: ["/bin/bash"]
  args:
    - -c
    - |
      set -euxo pipefail

      # Login with the api key
      ibmcloud login --apikey -${ibmcloud-api-token}

    
      # Set resource group, cf org and space
      ibmcloud target -g ${cf-org} -o ${cf-org} -s ${cf-space}
      
      # Clone application 
      git clone https://github.com/ibm-cloud-architecture/devops-demo-storefront-ui

      # Change directory to the clone app
      cd devops-demo-storefront-ui

      # Push app to cloud foundry
      cf push -f ./manifest.yml storefront-ui-app

  env:
    - name: namespace
      value: $(inputs.params.namespace)
    - name: cf-org
      value: $(inputs.params.cf-org)
    - name: cf-space
      value: $(inputs.params.cf-space)
    - name: cf-app-name
      value: $(inputs.params.cf-app-name)
    - name: ibmcloud-api-token
      valueFrom:
        secretKeyRef:
          name: ibm-cr-pull-secret
          key: PASSWORD
  resources: {}
  workingDir: $(inputs.resources.source.path)
